# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CPlusKitchen' do
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Material', '~> 1.0'
pod 'MaterialKit', '~> 0.4'
pod 'Alamofire', '~> 3.4'
pod 'AlamofireImage', '~> 2.0'
pod 'GoogleSignIn'
end

