# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CPlusKitchen' do
pod 'MaterialKit', '~> 0.4'
pod 'Material', '~> 1.0'
end

